### ISSUE TITLE
Layer 3 (altgr)

### ISSUE THREAD

**Issue by AKmatiAK** [cuppajoeman/x11-keyboard-layout-generator#1]
Hi, if it's easy to do you can add ability to map layer 3. It would be useful. Nice script btw.

**Comment by cuppajoeman** [comment]
Hey, @AKmatiAK do you think you could explain this a little more? 

What do you mean by "map layer 3" ?

**Comment by cuppajoeman** [comment]
Ok, I thought about this more and if I understand correctly you want to be able map more keys using the alt key for example.

I think that makes sense, and maybe later we should add the ability for even more than 3 layers using modifier keys. One way we could implement this is by having a key like `|1234|` (say on key q) in the layout and then iterating through those and creating the needed mappings in the layout file.

Anyways getting ahead of myself. @dmi3 I saw you forked this project, and looks like you might have added support for the alt layer?

If you have, would you be able to make a pull request with that feature?

**Comment by cuppajoeman** [comment]
@AKmatiAK we now have this functionality thanks to @dmi3
